### PR TITLE
Allow for even numbered arrays

### PR DESCRIPTION
**Pull request by leonsegal**
Hi

Hopefully all the requirements you set are met now!

Thanks
Leon

### CODE REVIEW

**Review by mazedlx — COMMENTED** [review]
Why use `$array`?

And please remove the whole `.idea` folder from your PR.

**Comment by leonsegal** [comment]
Just used $array as it was shorter - I will change it back to $this->array and remove the idea folder (I didn't realise it was in there - I thought the ignore file got it! Spot the newb)!

**Comment by leonsegal** [comment]
Just let me know what else I have to do and I will get on it!

Leon
:)

**Review by mazedlx — CHANGES_REQUESTED** [review]
One last thing: change the variables from snake_case to camelCase. 
Then we're good to go 😊

**Comment by leonsegal** [comment]
Done!

I also simplified the return statement of even numbered arrays by removing the average_of_midpoints variable, as it seemed redundant! 

:)

**Review by mazedlx — APPROVED** [review]
Thanks.

**Pull request merged**
