### PR TITLE
Fix median of even number array

### PR DESCRIPTION
**Pull request by leonsegal**
Hi

This is my first pull request (ever), so go gently on me haha!

I am using this library in a project and I noticed that if the array is even numbered length, then the result is not right - it should be the average of the 2 middle numbers.

I have fixed it and I am open to suggestion on my code as I am still learning!

**This is the 2nd pull request - I closed the 1st one as I used the array key instead of the array value!**

Thanks
Leon

### CODE REVIEW

**Comment by mazedlx** [comment]
Thank you for your PR. First. you should write a test in https://github.com/mazedlx/median/blob/master/spec/Median/MedianSpec.php for an array with an even number of elements. 

Second, please remove test code from the class. 
Third, why did you change the static method to a non static method? 
Fourth, please consider using the PHP-FIG PSR-2 standard.

**Comment by mazedlx** [comment]
Fourth, please consider sparing the PHP-FIG PSR-2 coding style.

**Comment by leonsegal** [comment]
No problem. Re your feedback:
1. I have written the tests now, but I am unsure how good they are
2. I thought I had removed all my test code - which part did you mean?
3. I changed the method to static purely for ease of local testing, I then changed it back so it was as I found it.
4. I thought I was using PSR2...which part of my code wasn't compliant?

Thanks
Leon

**Comment by leonsegal** [comment]
I will create a new pr - I have written the tests you wanted now.

**Pull request closed without merging**
